// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVTc-gRhbvc1vS4PJJ2kwyq37cZOhyHcQ',
    appId: '1:1001281655977:web:5fa953e193da2a8e5c45b8',
    messagingSenderId: '1001281655977',
    projectId: 'tomorrow-6e538',
    authDomain: 'tomorrow-6e538.firebaseapp.com',
    storageBucket: 'tomorrow-6e538.firebasestorage.app',
    measurementId: 'G-C7DYWDZJ8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8SQOe0CFym9ju2WHi34xB-RkkOZfGaQE',
    appId: '1:1001281655977:android:edf3cdb87bf7ffa75c45b8',
    messagingSenderId: '1001281655977',
    projectId: 'tomorrow-6e538',
    storageBucket: 'tomorrow-6e538.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoY8fZBJPAyl7BKCB6qRbfjBNDLWggQw4',
    appId: '1:1001281655977:ios:cb470f72d36973685c45b8',
    messagingSenderId: '1001281655977',
    projectId: 'tomorrow-6e538',
    storageBucket: 'tomorrow-6e538.firebasestorage.app',
    iosBundleId: 'com.tomorrow.tomorrow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoY8fZBJPAyl7BKCB6qRbfjBNDLWggQw4',
    appId: '1:1001281655977:ios:cb470f72d36973685c45b8',
    messagingSenderId: '1001281655977',
    projectId: 'tomorrow-6e538',
    storageBucket: 'tomorrow-6e538.firebasestorage.app',
    iosBundleId: 'com.tomorrow.tomorrow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVTc-gRhbvc1vS4PJJ2kwyq37cZOhyHcQ',
    appId: '1:1001281655977:web:b568169a1d51a8415c45b8',
    messagingSenderId: '1001281655977',
    projectId: 'tomorrow-6e538',
    authDomain: 'tomorrow-6e538.firebaseapp.com',
    storageBucket: 'tomorrow-6e538.firebasestorage.app',
    measurementId: 'G-7GP3GNCYFS',
  );
}
